[2024-09-01 19:09:54,390] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-03-14T00:00:00+00:00 [queued]>
[2024-09-01 19:09:54,580] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-03-14T00:00:00+00:00 [queued]>
[2024-09-01 19:09:54,587] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-09-01 19:09:54,595] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2024-09-01 19:09:54,597] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-09-01 19:09:54,902] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): run_main_script> on 2024-03-14 00:00:00+00:00
[2024-09-01 19:09:54,971] {standard_task_runner.py:52} INFO - Started process 693 to run task
[2024-09-01 19:09:55,021] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'exchange_rates_dag', 'run_main_script', 'scheduled__2024-03-14T00:00:00+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/exchange_rates_dag.py', '--cfg-path', '/tmp/tmps7l48237', '--error-file', '/tmp/tmpe_colihu']
[2024-09-01 19:09:55,059] {standard_task_runner.py:80} INFO - Job 76: Subtask run_main_script
[2024-09-01 19:09:56,020] {task_command.py:371} INFO - Running <TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-03-14T00:00:00+00:00 [running]> on host 6de2165e2444
[2024-09-01 19:09:57,171] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=exchange_rates_dag
AIRFLOW_CTX_TASK_ID=run_main_script
AIRFLOW_CTX_EXECUTION_DATE=2024-03-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-03-14T00:00:00+00:00
[2024-09-01 19:10:17,662] {python.py:173} INFO - Done. Returned value was: None
[2024-09-01 19:10:17,763] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=exchange_rates_dag, task_id=run_main_script, execution_date=20240314T000000, start_date=20240901T190954, end_date=20240901T191017
[2024-09-01 19:10:17,889] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-01 19:10:18,042] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15T05:55:09.184+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-15T05:55:09.329+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-03-14T00:00:00+00:00 [queued]>
[2024-09-15T05:55:09.419+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-03-14T00:00:00+00:00 [queued]>
[2024-09-15T05:55:09.424+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-15T05:55:09.806+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_main_script> on 2024-03-14 00:00:00+00:00
[2024-09-15T05:55:09.845+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=680) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-15T05:55:09.858+0000] {standard_task_runner.py:72} INFO - Started process 682 to run task
[2024-09-15T05:55:09.849+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'exchange_rates_dag', 'run_main_script', 'scheduled__2024-03-14T00:00:00+00:00', '--job-id', '196', '--raw', '--subdir', 'DAGS_FOLDER/exchange_rates_dag.py', '--cfg-path', '/tmp/tmp5i3r29n2']
[2024-09-15T05:55:09.869+0000] {standard_task_runner.py:105} INFO - Job 196: Subtask run_main_script
[2024-09-15T05:55:10.187+0000] {task_command.py:467} INFO - Running <TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-03-14T00:00:00+00:00 [running]> on host ed6b7035df5d
[2024-09-15T05:55:10.575+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***docker@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exchange_rates_dag' AIRFLOW_CTX_TASK_ID='run_main_script' AIRFLOW_CTX_EXECUTION_DATE='2024-03-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-14T00:00:00+00:00'
[2024-09-15T05:55:10.584+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-15T05:55:20.825+0000] {local_task_job_runner.py:127} ERROR - Received SIGTERM. Terminating subprocesses
[2024-09-15T05:55:21.039+0000] {process_utils.py:132} INFO - Sending 15 to group 682. PIDs of all processes in the group: [687, 682]
[2024-09-15T05:55:21.189+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 682
[2024-09-15T05:55:21.256+0000] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-09-15T05:55:22.079+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/exchange_rates_dag.py", line 29, in run_main
    subprocess.run(["python3", "/opt/airflow/main.py"], check=True)
  File "/usr/local/lib/python3.12/subprocess.py", line 550, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 1201, in communicate
    self.wait()
  File "/usr/local/lib/python3.12/subprocess.py", line 1264, in wait
    return self._wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 2053, in _wait
    (pid, sts) = self._try_wait(0)
                 ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 2011, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3094, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-09-15T05:55:22.264+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=687, status='terminated', started='05:55:10') (687) terminated with exit code None
[2024-09-15T05:55:22.508+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=exchange_rates_dag, task_id=run_main_script, run_id=scheduled__2024-03-14T00:00:00+00:00, execution_date=20240314T000000, start_date=20240915T055509, end_date=20240915T055522
[2024-09-15T05:55:23.189+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-15T05:55:23.554+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=682, status='terminated', exitcode=2, started='05:55:09') (682) terminated with exit code 2
[2024-09-15T05:55:23.593+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 143
[2024-09-15T05:55:24.620+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15T05:55:24.876+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2024-09-15T05:55:25.158+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
