[2024-09-08T15:39:04.562+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-08T15:39:04.909+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2024-09-08T15:39:05.015+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2024-09-08T15:39:05.029+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-08T15:39:05.169+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_main_script> on 2024-01-02 00:00:00+00:00
[2024-09-08T15:39:05.229+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=183) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-08T15:39:05.248+0000] {standard_task_runner.py:72} INFO - Started process 189 to run task
[2024-09-08T15:39:05.234+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'exchange_rates_dag', 'run_main_script', 'scheduled__2024-01-02T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/exchange_rates_dag.py', '--cfg-path', '/tmp/tmpb_bn23fj']
[2024-09-08T15:39:05.262+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask run_main_script
[2024-09-08T15:39:05.594+0000] {task_command.py:467} INFO - Running <TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-01-02T00:00:00+00:00 [running]> on host bd0133ae5e03
[2024-09-08T15:39:06.137+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exchange_rates_dag' AIRFLOW_CTX_TASK_ID='run_main_script' AIRFLOW_CTX_EXECUTION_DATE='2024-01-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-02T00:00:00+00:00'
[2024-09-08T15:39:06.148+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-08T15:40:38.030+0000] {local_task_job_runner.py:127} ERROR - Received SIGTERM. Terminating subprocesses
[2024-09-08T15:40:38.287+0000] {process_utils.py:132} INFO - Sending 15 to group 189. PIDs of all processes in the group: [194, 189]
[2024-09-08T15:40:38.361+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 189
[2024-09-08T15:40:38.378+0000] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-09-08T15:40:38.723+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=194, status='terminated', started='15:39:05') (194) terminated with exit code None
[2024-09-08T15:40:39.004+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/exchange_rates_dag.py", line 27, in run_main
    subprocess.run(["python3", "/opt/airflow/main.py"], check=True)
  File "/usr/local/lib/python3.12/subprocess.py", line 550, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 1201, in communicate
    self.wait()
  File "/usr/local/lib/python3.12/subprocess.py", line 1264, in wait
    return self._wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 2053, in _wait
    (pid, sts) = self._try_wait(0)
                 ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 2011, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3094, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-09-08T15:40:39.376+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=exchange_rates_dag, task_id=run_main_script, run_id=scheduled__2024-01-02T00:00:00+00:00, execution_date=20240102T000000, start_date=20240908T153904, end_date=20240908T154039
[2024-09-08T15:40:39.876+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-08T15:40:40.184+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=189, status='terminated', exitcode=2, started='15:39:04') (189) terminated with exit code 2
[2024-09-08T15:40:40.202+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 143
[2024-09-08T15:40:40.384+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2024-09-08T15:40:40.752+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-08T15:40:42.869+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
