[2024-09-01 19:19:23,210] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-08-18T00:00:00+00:00 [queued]>
[2024-09-01 19:19:23,224] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-08-18T00:00:00+00:00 [queued]>
[2024-09-01 19:19:23,225] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-09-01 19:19:23,229] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2024-09-01 19:19:23,231] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-09-01 19:19:23,266] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): run_main_script> on 2024-08-18 00:00:00+00:00
[2024-09-01 19:19:23,281] {standard_task_runner.py:52} INFO - Started process 731 to run task
[2024-09-01 19:19:23,293] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'exchange_rates_dag', 'run_main_script', 'scheduled__2024-08-18T00:00:00+00:00', '--job-id', '247', '--raw', '--subdir', 'DAGS_FOLDER/exchange_rates_dag.py', '--cfg-path', '/tmp/tmp_ft4szpl', '--error-file', '/tmp/tmpj4nx71x3']
[2024-09-01 19:19:23,299] {standard_task_runner.py:80} INFO - Job 247: Subtask run_main_script
[2024-09-01 19:19:23,616] {task_command.py:371} INFO - Running <TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-08-18T00:00:00+00:00 [running]> on host 6de2165e2444
[2024-09-01 19:19:24,007] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=exchange_rates_dag
AIRFLOW_CTX_TASK_ID=run_main_script
AIRFLOW_CTX_EXECUTION_DATE=2024-08-18T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-08-18T00:00:00+00:00
[2024-09-01 19:19:41,396] {python.py:173} INFO - Done. Returned value was: None
[2024-09-01 19:19:43,715] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=exchange_rates_dag, task_id=run_main_script, execution_date=20240818T000000, start_date=20240901T191923, end_date=20240901T191943
[2024-09-01 19:19:44,018] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-01 19:19:44,364] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15T06:03:15.830+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-15T06:03:15.940+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-08-18T00:00:00+00:00 [queued]>
[2024-09-15T06:03:16.025+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-08-18T00:00:00+00:00 [queued]>
[2024-09-15T06:03:16.031+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-15T06:03:16.610+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_main_script> on 2024-08-18 00:00:00+00:00
[2024-09-15T06:03:16.660+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=405) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-15T06:03:16.670+0000] {standard_task_runner.py:72} INFO - Started process 416 to run task
[2024-09-15T06:03:16.662+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'exchange_rates_dag', 'run_main_script', 'scheduled__2024-08-18T00:00:00+00:00', '--job-id', '256', '--raw', '--subdir', 'DAGS_FOLDER/exchange_rates_dag.py', '--cfg-path', '/tmp/tmp2c36pjfh']
[2024-09-15T06:03:16.681+0000] {standard_task_runner.py:105} INFO - Job 256: Subtask run_main_script
[2024-09-15T06:03:16.953+0000] {task_command.py:467} INFO - Running <TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-08-18T00:00:00+00:00 [running]> on host ed6b7035df5d
[2024-09-15T06:03:17.477+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***docker@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exchange_rates_dag' AIRFLOW_CTX_TASK_ID='run_main_script' AIRFLOW_CTX_EXECUTION_DATE='2024-08-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-18T00:00:00+00:00'
[2024-09-15T06:03:17.493+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-15T06:05:05.423+0000] {local_task_job_runner.py:127} ERROR - Received SIGTERM. Terminating subprocesses
[2024-09-15T06:05:05.766+0000] {process_utils.py:132} INFO - Sending 15 to group 416. PIDs of all processes in the group: [419, 416]
[2024-09-15T06:05:05.816+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 416
[2024-09-15T06:05:05.884+0000] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-09-15T06:05:06.390+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=419, status='terminated', started='06:03:16') (419) terminated with exit code None
[2024-09-15T06:05:06.588+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/exchange_rates_dag.py", line 30, in run_main
    subprocess.run(["python3", "/opt/airflow/main.py"], check=True)
  File "/usr/local/lib/python3.12/subprocess.py", line 550, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 1201, in communicate
    self.wait()
  File "/usr/local/lib/python3.12/subprocess.py", line 1264, in wait
    return self._wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 2053, in _wait
    (pid, sts) = self._try_wait(0)
                 ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 2011, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3094, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-09-15T06:05:07.015+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=exchange_rates_dag, task_id=run_main_script, run_id=scheduled__2024-08-18T00:00:00+00:00, execution_date=20240818T000000, start_date=20240915T060315, end_date=20240915T060506
[2024-09-15T06:05:08.364+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-15T06:05:08.688+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=416, status='terminated', exitcode=2, started='06:03:15') (416) terminated with exit code 2
[2024-09-15T06:05:08.709+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 143
[2024-09-15T06:05:09.481+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15T06:05:09.820+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
