[2024-09-01 19:09:48,163] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-03-10T00:00:00+00:00 [queued]>
[2024-09-01 19:09:48,299] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-03-10T00:00:00+00:00 [queued]>
[2024-09-01 19:09:48,314] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-09-01 19:09:48,320] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2024-09-01 19:09:48,325] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-09-01 19:09:48,492] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): run_main_script> on 2024-03-10 00:00:00+00:00
[2024-09-01 19:09:48,531] {standard_task_runner.py:52} INFO - Started process 672 to run task
[2024-09-01 19:09:48,572] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'exchange_rates_dag', 'run_main_script', 'scheduled__2024-03-10T00:00:00+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/exchange_rates_dag.py', '--cfg-path', '/tmp/tmpsq9jrvwh', '--error-file', '/tmp/tmpxc7mi6cd']
[2024-09-01 19:09:48,585] {standard_task_runner.py:80} INFO - Job 72: Subtask run_main_script
[2024-09-01 19:09:49,318] {task_command.py:371} INFO - Running <TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-03-10T00:00:00+00:00 [running]> on host 6de2165e2444
[2024-09-01 19:09:50,186] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=exchange_rates_dag
AIRFLOW_CTX_TASK_ID=run_main_script
AIRFLOW_CTX_EXECUTION_DATE=2024-03-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-03-10T00:00:00+00:00
[2024-09-01 19:10:11,940] {python.py:173} INFO - Done. Returned value was: None
[2024-09-01 19:10:12,187] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=exchange_rates_dag, task_id=run_main_script, execution_date=20240310T000000, start_date=20240901T190948, end_date=20240901T191012
[2024-09-01 19:10:12,463] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-01 19:10:14,016] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15T05:54:40.701+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-15T05:54:40.926+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-03-10T00:00:00+00:00 [queued]>
[2024-09-15T05:54:40.998+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-03-10T00:00:00+00:00 [queued]>
[2024-09-15T05:54:41.011+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-15T05:54:41.997+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_main_script> on 2024-03-10 00:00:00+00:00
[2024-09-15T05:54:42.081+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=635) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-15T05:54:42.096+0000] {standard_task_runner.py:72} INFO - Started process 643 to run task
[2024-09-15T05:54:42.071+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'exchange_rates_dag', 'run_main_script', 'scheduled__2024-03-10T00:00:00+00:00', '--job-id', '188', '--raw', '--subdir', 'DAGS_FOLDER/exchange_rates_dag.py', '--cfg-path', '/tmp/tmp5iwpfj3u']
[2024-09-15T05:54:42.103+0000] {standard_task_runner.py:105} INFO - Job 188: Subtask run_main_script
[2024-09-15T05:54:42.523+0000] {task_command.py:467} INFO - Running <TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-03-10T00:00:00+00:00 [running]> on host ed6b7035df5d
[2024-09-15T05:54:43.505+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***docker@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exchange_rates_dag' AIRFLOW_CTX_TASK_ID='run_main_script' AIRFLOW_CTX_EXECUTION_DATE='2024-03-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-10T00:00:00+00:00'
[2024-09-15T05:54:43.523+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-15T05:55:20.813+0000] {local_task_job_runner.py:127} ERROR - Received SIGTERM. Terminating subprocesses
[2024-09-15T05:55:21.022+0000] {process_utils.py:132} INFO - Sending 15 to group 643. PIDs of all processes in the group: [650, 643]
[2024-09-15T05:55:21.140+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 643
[2024-09-15T05:55:21.195+0000] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-09-15T05:55:21.723+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=650, status='terminated', started='05:54:43') (650) terminated with exit code None
[2024-09-15T05:55:22.076+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/exchange_rates_dag.py", line 29, in run_main
    subprocess.run(["python3", "/opt/airflow/main.py"], check=True)
  File "/usr/local/lib/python3.12/subprocess.py", line 550, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 1201, in communicate
    self.wait()
  File "/usr/local/lib/python3.12/subprocess.py", line 1264, in wait
    return self._wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 2053, in _wait
    (pid, sts) = self._try_wait(0)
                 ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 2011, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3094, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-09-15T05:55:22.502+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=exchange_rates_dag, task_id=run_main_script, run_id=scheduled__2024-03-10T00:00:00+00:00, execution_date=20240310T000000, start_date=20240915T055440, end_date=20240915T055522
[2024-09-15T05:55:23.122+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-15T05:55:23.391+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=643, status='terminated', exitcode=2, started='05:54:41') (643) terminated with exit code 2
[2024-09-15T05:55:23.423+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 143
[2024-09-15T05:55:24.419+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15T05:55:24.693+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
