[2024-09-01 19:19:24,268] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-08-19T00:00:00+00:00 [queued]>
[2024-09-01 19:19:24,336] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-08-19T00:00:00+00:00 [queued]>
[2024-09-01 19:19:24,340] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-09-01 19:19:24,346] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2024-09-01 19:19:24,349] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-09-01 19:19:24,441] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): run_main_script> on 2024-08-19 00:00:00+00:00
[2024-09-01 19:19:24,464] {standard_task_runner.py:52} INFO - Started process 736 to run task
[2024-09-01 19:19:24,508] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'exchange_rates_dag', 'run_main_script', 'scheduled__2024-08-19T00:00:00+00:00', '--job-id', '248', '--raw', '--subdir', 'DAGS_FOLDER/exchange_rates_dag.py', '--cfg-path', '/tmp/tmp21rs46f3', '--error-file', '/tmp/tmp9aapmdby']
[2024-09-01 19:19:24,524] {standard_task_runner.py:80} INFO - Job 248: Subtask run_main_script
[2024-09-01 19:19:25,280] {task_command.py:371} INFO - Running <TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-08-19T00:00:00+00:00 [running]> on host 6de2165e2444
[2024-09-01 19:19:26,463] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=exchange_rates_dag
AIRFLOW_CTX_TASK_ID=run_main_script
AIRFLOW_CTX_EXECUTION_DATE=2024-08-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-08-19T00:00:00+00:00
[2024-09-01 19:19:47,212] {python.py:173} INFO - Done. Returned value was: None
[2024-09-01 19:19:47,758] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=exchange_rates_dag, task_id=run_main_script, execution_date=20240819T000000, start_date=20240901T191924, end_date=20240901T191947
[2024-09-01 19:19:48,347] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-01 19:19:49,196] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15T06:03:16.575+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-15T06:03:16.671+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-08-19T00:00:00+00:00 [queued]>
[2024-09-15T06:03:16.736+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-08-19T00:00:00+00:00 [queued]>
[2024-09-15T06:03:16.743+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-15T06:03:17.624+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_main_script> on 2024-08-19 00:00:00+00:00
[2024-09-15T06:03:17.667+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=409) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-15T06:03:17.682+0000] {standard_task_runner.py:72} INFO - Started process 420 to run task
[2024-09-15T06:03:17.665+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'exchange_rates_dag', 'run_main_script', 'scheduled__2024-08-19T00:00:00+00:00', '--job-id', '257', '--raw', '--subdir', 'DAGS_FOLDER/exchange_rates_dag.py', '--cfg-path', '/tmp/tmpoqk3t3yc']
[2024-09-15T06:03:17.689+0000] {standard_task_runner.py:105} INFO - Job 257: Subtask run_main_script
[2024-09-15T06:03:17.893+0000] {task_command.py:467} INFO - Running <TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-08-19T00:00:00+00:00 [running]> on host ed6b7035df5d
[2024-09-15T06:03:18.368+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***docker@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exchange_rates_dag' AIRFLOW_CTX_TASK_ID='run_main_script' AIRFLOW_CTX_EXECUTION_DATE='2024-08-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-19T00:00:00+00:00'
[2024-09-15T06:03:18.380+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-15T06:05:05.481+0000] {local_task_job_runner.py:127} ERROR - Received SIGTERM. Terminating subprocesses
[2024-09-15T06:05:05.817+0000] {process_utils.py:132} INFO - Sending 15 to group 420. PIDs of all processes in the group: [424, 420]
[2024-09-15T06:05:05.895+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 420
[2024-09-15T06:05:05.953+0000] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-09-15T06:05:06.500+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=424, status='terminated', started='06:03:17') (424) terminated with exit code None
[2024-09-15T06:05:06.626+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/exchange_rates_dag.py", line 30, in run_main
    subprocess.run(["python3", "/opt/airflow/main.py"], check=True)
  File "/usr/local/lib/python3.12/subprocess.py", line 550, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 1201, in communicate
    self.wait()
  File "/usr/local/lib/python3.12/subprocess.py", line 1264, in wait
    return self._wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 2053, in _wait
    (pid, sts) = self._try_wait(0)
                 ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 2011, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3094, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-09-15T06:05:07.053+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=exchange_rates_dag, task_id=run_main_script, run_id=scheduled__2024-08-19T00:00:00+00:00, execution_date=20240819T000000, start_date=20240915T060316, end_date=20240915T060506
[2024-09-15T06:05:08.428+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-15T06:05:08.683+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=420, status='terminated', exitcode=2, started='06:03:16') (420) terminated with exit code 2
[2024-09-15T06:05:08.702+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 143
[2024-09-15T06:05:09.488+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15T06:05:09.813+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
