[2024-09-01 19:19:28,289] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-08-24T00:00:00+00:00 [queued]>
[2024-09-01 19:19:28,491] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-08-24T00:00:00+00:00 [queued]>
[2024-09-01 19:19:28,505] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-09-01 19:19:28,508] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2024-09-01 19:19:28,515] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-09-01 19:19:28,770] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): run_main_script> on 2024-08-24 00:00:00+00:00
[2024-09-01 19:19:28,837] {standard_task_runner.py:52} INFO - Started process 752 to run task
[2024-09-01 19:19:28,896] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'exchange_rates_dag', 'run_main_script', 'scheduled__2024-08-24T00:00:00+00:00', '--job-id', '253', '--raw', '--subdir', 'DAGS_FOLDER/exchange_rates_dag.py', '--cfg-path', '/tmp/tmpmgqog5w7', '--error-file', '/tmp/tmpfnrbn1po']
[2024-09-01 19:19:28,936] {standard_task_runner.py:80} INFO - Job 253: Subtask run_main_script
[2024-09-01 19:19:29,894] {task_command.py:371} INFO - Running <TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-08-24T00:00:00+00:00 [running]> on host 6de2165e2444
[2024-09-01 19:19:30,978] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=exchange_rates_dag
AIRFLOW_CTX_TASK_ID=run_main_script
AIRFLOW_CTX_EXECUTION_DATE=2024-08-24T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-08-24T00:00:00+00:00
[2024-09-01 19:19:54,758] {python.py:173} INFO - Done. Returned value was: None
[2024-09-01 19:19:54,901] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=exchange_rates_dag, task_id=run_main_script, execution_date=20240824T000000, start_date=20240901T191928, end_date=20240901T191954
[2024-09-01 19:19:55,028] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-01 19:19:55,260] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15T06:03:50.742+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-15T06:03:50.824+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-08-24T00:00:00+00:00 [queued]>
[2024-09-15T06:03:50.873+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-08-24T00:00:00+00:00 [queued]>
[2024-09-15T06:03:50.881+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-15T06:03:50.953+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_main_script> on 2024-08-24 00:00:00+00:00
[2024-09-15T06:03:51.003+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=455) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-15T06:03:51.010+0000] {standard_task_runner.py:72} INFO - Started process 459 to run task
[2024-09-15T06:03:51.001+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'exchange_rates_dag', 'run_main_script', 'scheduled__2024-08-24T00:00:00+00:00', '--job-id', '266', '--raw', '--subdir', 'DAGS_FOLDER/exchange_rates_dag.py', '--cfg-path', '/tmp/tmpkrugncjm']
[2024-09-15T06:03:51.021+0000] {standard_task_runner.py:105} INFO - Job 266: Subtask run_main_script
[2024-09-15T06:03:51.294+0000] {task_command.py:467} INFO - Running <TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-08-24T00:00:00+00:00 [running]> on host ed6b7035df5d
[2024-09-15T06:03:51.897+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***docker@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exchange_rates_dag' AIRFLOW_CTX_TASK_ID='run_main_script' AIRFLOW_CTX_EXECUTION_DATE='2024-08-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-24T00:00:00+00:00'
[2024-09-15T06:03:51.909+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-15T06:05:05.478+0000] {local_task_job_runner.py:127} ERROR - Received SIGTERM. Terminating subprocesses
[2024-09-15T06:05:05.779+0000] {process_utils.py:132} INFO - Sending 15 to group 459. PIDs of all processes in the group: [462, 459]
[2024-09-15T06:05:05.822+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 459
[2024-09-15T06:05:05.886+0000] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-09-15T06:05:06.394+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=462, status='terminated', started='06:03:51') (462) terminated with exit code None
[2024-09-15T06:05:06.671+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/exchange_rates_dag.py", line 30, in run_main
    subprocess.run(["python3", "/opt/airflow/main.py"], check=True)
  File "/usr/local/lib/python3.12/subprocess.py", line 550, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 1201, in communicate
    self.wait()
  File "/usr/local/lib/python3.12/subprocess.py", line 1264, in wait
    return self._wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 2053, in _wait
    (pid, sts) = self._try_wait(0)
                 ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 2011, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3094, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-09-15T06:05:07.081+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=exchange_rates_dag, task_id=run_main_script, run_id=scheduled__2024-08-24T00:00:00+00:00, execution_date=20240824T000000, start_date=20240915T060350, end_date=20240915T060507
[2024-09-15T06:05:08.390+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-15T06:05:08.686+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=459, status='terminated', exitcode=2, started='06:03:50') (459) terminated with exit code 2
[2024-09-15T06:05:08.707+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 143
[2024-09-15T06:05:09.502+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15T06:05:09.878+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
