[2024-09-01 19:13:33,607] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-06-11T00:00:00+00:00 [queued]>
[2024-09-01 19:13:33,858] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-06-11T00:00:00+00:00 [queued]>
[2024-09-01 19:13:33,875] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-09-01 19:13:33,880] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2024-09-01 19:13:33,885] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-09-01 19:13:34,275] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): run_main_script> on 2024-06-11 00:00:00+00:00
[2024-09-01 19:13:34,349] {standard_task_runner.py:52} INFO - Started process 1335 to run task
[2024-09-01 19:13:34,473] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'exchange_rates_dag', 'run_main_script', 'scheduled__2024-06-11T00:00:00+00:00', '--job-id', '167', '--raw', '--subdir', 'DAGS_FOLDER/exchange_rates_dag.py', '--cfg-path', '/tmp/tmpc89wm0tl', '--error-file', '/tmp/tmp_epe0sxw']
[2024-09-01 19:13:34,513] {standard_task_runner.py:80} INFO - Job 167: Subtask run_main_script
[2024-09-01 19:13:35,884] {task_command.py:371} INFO - Running <TaskInstance: exchange_rates_dag.run_main_script scheduled__2024-06-11T00:00:00+00:00 [running]> on host 6de2165e2444
[2024-09-01 19:13:37,494] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=exchange_rates_dag
AIRFLOW_CTX_TASK_ID=run_main_script
AIRFLOW_CTX_EXECUTION_DATE=2024-06-11T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-06-11T00:00:00+00:00
[2024-09-01 19:13:41,321] {local_task_job.py:84} ERROR - Received SIGTERM. Terminating subprocesses
[2024-09-01 19:13:41,532] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 1335. PIDs of all processes in the group: [1343, 1335]
[2024-09-01 19:13:41,617] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 1335
[2024-09-01 19:13:41,638] {taskinstance.py:1561} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-09-01 19:13:42,148] {process_utils.py:75} INFO - Process psutil.Process(pid=1343, status='terminated', started='19:13:36') (1343) terminated with exit code None
[2024-09-01 19:13:42,264] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/exchange_rates_dag.py", line 27, in run_main
    subprocess.run(["python3", "/opt/airflow/main.py"], check=True)
  File "/usr/local/lib/python3.7/subprocess.py", line 490, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/local/lib/python3.7/subprocess.py", line 956, in communicate
    self.wait()
  File "/usr/local/lib/python3.7/subprocess.py", line 1019, in wait
    return self._wait(timeout=timeout)
  File "/usr/local/lib/python3.7/subprocess.py", line 1653, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/local/lib/python3.7/subprocess.py", line 1611, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1563, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-09-01 19:13:42,388] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=exchange_rates_dag, task_id=run_main_script, execution_date=20240611T000000, start_date=20240901T191333, end_date=20240901T191342
[2024-09-01 19:13:42,810] {standard_task_runner.py:97} ERROR - Failed to execute job 167 for task run_main_script (Task received SIGTERM signal; 1335)
[2024-09-01 19:13:42,975] {process_utils.py:75} INFO - Process psutil.Process(pid=1335, status='terminated', exitcode=1, started='19:13:33') (1335) terminated with exit code 1
[2024-09-01 19:13:42,996] {local_task_job.py:156} INFO - Task exited with return code 143
[2024-09-01 19:13:43,990] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
